List<String> mensAvatars = [
  'assets/images/man-1.png',
  'assets/images/man-2.png',
  'assets/images/man-3.png',
  'assets/images/man-4.png',
  'assets/images/man-5.png',
  'assets/images/man-6.png',
  'assets/images/man-7.png',
  'assets/images/man-8.png',
  'assets/images/man-9.png',
  'assets/images/man-10.png',
  'assets/images/man-11.png',
  'assets/images/man-12.png',
  'assets/images/man-13.png',
  'assets/images/man-14.png',
  'assets/images/man-15.png',
];

List<String> womensAvatars = [
  'assets/images/woman-1.png',
  'assets/images/woman-2.png',
  'assets/images/woman-3.png',
  'assets/images/woman-4.png',
  'assets/images/woman-5.png',
  'assets/images/woman-6.png',
  'assets/images/woman-7.png',
  'assets/images/woman-8.png',
  'assets/images/woman-9.png',
  'assets/images/woman-10.png',
  'assets/images/woman-11.png',
  'assets/images/woman-12.png',
  'assets/images/woman-13.png',
  'assets/images/woman-14.png',
  'assets/images/woman-15.png',
];